---
- name: Install Kubernetes utilities and deploy NiFi Stack
  hosts: installationhost
  become: true
  gather_facts: yes

  vars:
    docker_secret_namespaces:
      - cfm-operator-system
      - demo-nifi
      - demo-nifi-registry
      - csa-operator-system
      - cloudera-kafka-demo
    openldap_secret_namespaces:
      - demo-nifi
      - demo-nifi-registry

  tasks:
    - name: Add Jetstack Helm repo
      shell: helm repo add jetstack https://charts.jetstack.io --force-update

    - name: Install cert-manager with CRDs
      shell: |
        helm install cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --create-namespace \
          --set crds.enabled=true

    - name: Deploy ClusterIssuer for cert-manager
      copy:
        dest: /tmp/clusterissuer.yaml
        content: |
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: self-signed-ca-issuer
          spec:
            selfSigned: {}
    - name: Apply ClusterIssuer
      shell: kubectl apply -f /tmp/clusterissuer.yaml

    - name: Ensure required namespaces exist
      shell: kubectl create namespace {{ item }} --dry-run=client -o yaml | kubectl apply -f -
      loop: "{{ docker_secret_namespaces }}"

    - name: Create Docker registry secrets in required namespaces
      shell: >
        kubectl create secret docker-registry docker-pull-secret
        --namespace {{ item }}
        --docker-server=container.repository.cloudera.com
        --docker-username={{ Cloudera_username }}
        --docker-password={{ Cloudera_password }}
        --dry-run=client -o yaml | kubectl apply -f -
      loop: "{{ docker_secret_namespaces }}"

    

    - name: Create OpenLDAP secret for NiFi
      shell: |
        kubectl create secret generic openldap-creds \
          --from-literal=managerPassword={{ ldapadmin_password }} \
          -n demo-nifi \
          --dry-run=client -o yaml | kubectl apply -f -
      loop: "{{ openldap_secret_namespaces }}"
    
    - name: Render and copy multiple Jinja2 templates
      template:
        src: "{{ item }}"
        dest: "/tmp/{{ item | regex_replace('.j2$', '') }}"
        mode: '0644'
      loop:
        - flink-deployment.yaml.j2
        - kafka.yaml.j2
        - nifi_overrides.yaml.j2
        - nifiregistry.yaml.j2
        - nodepool-broker.yaml.j2
        - nodepool-controller.yaml.j2
