---
apiVersion: cfm.cloudera.com/v1alpha1
kind: NifiRegistry
metadata:
  name: demonifiregistry
spec:
  image:
    repository: container.repository.cloudera.com/cloudera/cfm-nifiregistry-k8s
    tag: 2.8.0-b94-nifi_1.25.0.2.3.13.0-36
    pullSecret: docker-pull-secret
  tiniImage:
    repository: container.repository.cloudera.com/cloudera/cfm-tini
    tag: 2.8.0-b94
    pullSecret: docker-pull-secret
  hostName: demonifiregistry.local
  security:
    ldap:
      authenticationStrategy: SIMPLE
      managerDN: cn=admin,dc=example,dc=org
      secretName: openldap-creds
      referralStrategy: FOLLOW
      connectTimeout: 3 secs
      readTimeout: 10 secs
      url: ldap://openldap.openldap.svc.cluster.local:389
      userSearchBase: dc=example,dc=org
      userSearchFilter: (uid={0})
      identityStrategy: USE_USERNAME
      authenticationExpiration: 12 hours
      sync:
        interval: 1 min
        userObjectClass: inetOrgPerson
        userSearchScope: SUBTREE
        userIdentityAttribute: cn
        userGroupNameAttribute: ou
        userGroupNameReferencedGroupAttribute: ou
        groupSearchBase: dc=example,dc=org
        groupObjectClass: organizationalUnit
        groupSearchScope: OBJECT
        groupNameAttribute: ou
    initialAdminIdentity: nifiadmin
    nodeCertGen:
      issuerRef:
        name: self-signed-ca-issuer
        kind: ClusterIssuer
  uiConnection:
    type: Ingress
    ingressConfig:
      ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/proxy-body-size: 700m
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
