= Accessing CDP Private Cloud

From the Cloudera Manager screen, click on **Data Services (New)** in the left pane.

On the **CDP Private Cloud Containerized Services** page, click on the **Open CDP Private Cloud Data Services** button. This will open the **CDP PvC authentication** page.

== Authentication

On the **PvC DS Authentication Page**, if you have LDAP account credentials, enter your username and password, then click on **Login**. Alternatively, click on **Login as Local Administrator** and enter the default credentials (`admin/admin`).

Login to **CDP Private Cloud Data Services** as local administrator (`admin/admin`).

After authenticating successfully, you will land at the **CDP Console/Data Services** page. From this page, you can navigate to different data services and the management services. Click on the **Management Console**.

== Changing Password

On the **Welcome to CDP Private Cloud** page, click **Reset Password** to change the Local Administrator Account password. Alternatively, navigate to **Administration > Authentication** on the **Management Console** page and click **Reset Password** to change the Local Administrator Account password.

== Configuring LDAP Authentication

Set up external authentication using the URL of the LDAP server and a CA certificate (if using an existing LDAP server and not proceeding with FreeIPA setup). Example:

`ldap://<ipa_or_ldap_server_fqdn>:389/`

Learn more about LDAP user authentication for CDP Private Cloud.

Enter values for LDAP authentication as mentioned in the table below:

[cols="2,3"]
|===
| Component | Value
| Authentication Backend Order | Database then EXTERNAL
| Authorization Backend Order | Database and EXTERNAL
| External Authentication Type | LDAP
| LDAP URL | `ldap://ipaserver.cldrsetup.local:389/`
| LDAP Bind User Distinguished Name | `uid=admin,cn=users,cn=accounts,dc=cldrsetup,dc=local`
| LDAP Bind Password | `<vmware123>` (password for KDC admin, configured earlier)
| Active Directory Domain (For AD-Based LDAP) | `<AD DOMAIN>`
| LDAP User Search Filter | `(&(uid={0})(objectClass=person))`
| LDAP User Search Base | `cn=users,cn=accounts,dc=cldrsetup,dc=local`
| LDAP Group Search Filter | `(&(member={1})(objectClass=posixgroup))`
| LDAP Group Search Base | `cn=groups,cn=accounts,dc=cldrsetup,dc=local`
| LDAP Distinguished Name Pattern | `uid=admin,cn=users,cn=accounts,dc=cldrsetup,dc=local`
|===

Follow the instructions on the **Welcome to CDP Private Cloud** page to complete this step.

Click **Test Connection** to ensure that you are able to connect to the configured LDAP server.

== User and Group Management

The **User Management** tab allows users to add or update roles on existing users. The **Groups** tab allows users to sync user groups from the active directory to access CDP Data Services.

For more details on Cloudera Private Cloud Management Console, visit: [https://docs.cloudera.com/management-console/1.5.4/index.html](https://docs.cloudera.com/management-console/1.5.4/index.html)

== Registering the Environment

After successfully configuring and testing the LDAP integration, the page will auto-redirect to the **Register Environment** page. If not, navigate to the **Environments** page and select **Register Environment**.

Provide the **Cloudera Manager** details and credentials to register the PvC Base Cluster **DataLake/Control Plane** environment to Data Services.

Click **Choose Cluster**, select the **PvC Base Cluster** from the populated list, and click **Register**.

== Accessing CDP Private Cloud Data Services

To access CDP Private Cloud Data Services:

1. From the **Cloudera Manager** screen, click on **Data Services (New)** in the left pane.
2. Click on **Open Private Cloud Data Services** to launch your **CDP Private Cloud Data Services** instance.
3. Log in using the default username and password (`admin/admin`).
4. Click **Launch CDP** to launch **CDP Private Cloud**.
5. In the **Welcome to CDP Private Cloud** page, click **Change Password** to change the **Local Administrator Account** password.
6. Set up external authentication using the URL of the LDAP server and a CA certificate of your secure LDAP.
7. Follow the instructions on the **Welcome to CDP Private Cloud** page to complete this step.
8. Click **Test Connection** to ensure that you are able to connect to the configured LDAP server.

== Additional Steps

- **Register a CDP Private Cloud environment**
- **Create your first Virtual Warehouse in the CDW Data Service**
- **Provision an ML Workspace in the CML Data Service**
- **Add a CDE service in the CDE Data Service**

**************************************************************************************************************

