= Appendix

This appendix contains the following:

== Appendix A – References Used in Guide

*Cloudera Private Cloud Base Getting Started Guide:*
https://docs.cloudera.com/cdp-private-cloud/latest/index.html

*Cloudera Private Cloud Data Services Getting Started Guide:*
https://docs.cloudera.com/cdp-private-cloud-data-services/latest/index.html

*CDP Private Cloud Machine Learning Overview:*
https://docs.cloudera.com/machine-learning/1.5.4/index.html

*CDP Private Cloud Data Engineering Overview:*
https://docs.cloudera.com/data-engineering/1.5.4/index.html

*CDP Private Cloud Data Warehouse Overview:*
https://docs.cloudera.com/data-warehouse/1.5.4/index.html

== Appendix B – Glossary of Terms

This glossary addresses some terms used in this document to aid understanding. It is not a complete list of all multi-cloud terminology. Some VMware product links are included for clarity.

=== Ansible
An infrastructure automation tool used to configure IT service components such as VMs on an IaaS platform.
https://www.ansible.com

=== AWS (Amazon Web Services)
Provider of IaaS and PaaS.
https://aws.amazon.com

=== Azure
Microsoft IaaS and PaaS.
https://azure.microsoft.com/en-gb/

=== Containers (Docker)
A means to package application code and dependencies for platform-agnostic execution.
https://www.docker.com
https://www.cisco.com/c/en/us/products/cloud-systems-management/containerplatform/index.html

=== DevOps
Principle of collaboration between development and operations teams with automated toolchains.
https://en.wikipedia.org/wiki/DevOps
https://en.wikipedia.org/wiki/CI/CD

=== IaaS (Infrastructure as-a-Service)
Infrastructure components provided as a service, typically accessed over the Internet.

=== IaC (Infrastructure as-Code)
Automation of infrastructure using code such as Ansible playbooks and Terraform.
https://en.wikipedia.org/wiki/Infrastructure_as_code

=== IAM (Identity and Access Management)
Control access to IT resources for authorized users.
https://en.wikipedia.org/wiki/Identity_management

=== GCP (Google Cloud Platform)
Google's IaaS and PaaS offering.
https://cloud.google.com/gcp

=== Kubernetes (K8s)
An open-source system for automating containerized application management.
https://kubernetes.io

=== Microservices
A software architecture consisting of small, independently deployable services.
https://en.wikipedia.org/wiki/Microservices

=== PaaS (Platform-as-a-Service)
A value-added service layer for application development and lifecycle management.

=== Private On-Premises Data Center
A data center housed within an enterprise, offering controlled access and security.

=== REST API
APIs accessed over HTTP(S) for distributed systems.
https://en.wikipedia.org/wiki/Representational_state_transfer

=== SaaS (Software-as-a-Service)
Applications provided as a service over the Internet.

=== SAML (Security Assertion Markup Language)
Protocol for SSO authentication and authorization.
https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language

=== Terraform
An open-source IaC tool for cloud services.
https://www.terraform.io

== Appendix C – Glossary of Acronyms

ACL—Access-Control List
AD—Microsoft Active Directory
API—Application Programming Interface
CDP – Cloudera Data Platform
CDP Private Cloud – Cloudera Data Platform Private Cloud
CDP Private Cloud DS – Cloudera Data Platform Private Cloud Data Services
CDW – Cloudera Data Warehouse
CML – Cloudera Machine Learning
CDE – Cloudera Data Engineering
CPU—Central Processing Unit
DC—Data Center
DHCP—Dynamic Host Configuration Protocol
DNS—Domain Name System
HA—High-Availability
ICMP—Internet Control Message Protocol
LAN—Local Area Network
MAC—Media Access Control Address (OSI Layer 2 Address)
MTU—Maximum Transmission Unit
NAT—Network Address Translation
OSI—Open Systems Interconnection model
RHEL – Red Hat Enterprise Linux
Syslog—System Logging Protocol
TCP—Transmission Control Protocol (OSI Layer 4)
UDP—User Datagram Protocol (OSI Layer 4)
URL—Uniform Resource Locator
VM—Virtual Machine
VPN—Virtual Private Network

== Cloudera Data Platform Private Cloud Resources

For Cloudera Data Platform Private Cloud latest release notes:
https://docs.cloudera.com/cdp-private-cloud-upgrade/latest/release-guide/topics/cdpdc-release-notes-links.html

For Cloudera Data Platform Private Cloud Base requirements and supported versions:
https://docs.cloudera.com/cdp-private-cloud-upgrade/latest/release-guide/topics/cdpdc-requirements-supported-versions.html

For Cloudera Data Platform Private Cloud Data Services installation requirements and supported versions:
https://docs.cloudera.com/cdp-private-cloud-data-services/1.5.4/index.html

