= CDP PvC Data Services ECS Cluster Error Handling

== References

* https://spacelift.io/blog/kubectl-port-forward
* https://docs.cloudera.com/cdp-private-cloud-data-services/1.5.4/day-two-operations/cdppvc-data-services-day-two-operations.pdf
* https://docs.cloudera.com/cdp-private-cloud-data-services/1.5.1/managing-ecs/cm-manage-ecs.pdf
* https://docs.cloudera.com/documentation/other/reference-architecture/PDF/cloudera_ref_arch_cdp_dc.pdf
* https://docs.cloudera.com/cdp-private-cloud-data-services/1.5.4/upgrade-ecs/cdppvc-upgrade-ecs.pdf

== Errors and Solutions

=== Connection Refused Error

.Error Message:
```
Could not get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```

.Solution:
```shell
[root@pvcecs-master ~]# journalctl -xeu kubelet
[root@pvcecs-master ~]# mkdir -p ~/.kube && cp /etc/rancher/rke2/rke2.yaml ~/.kube/config
[root@pvcecs-master ~]# export PATH=/var/lib/rancher/rke2/data/v1.26.10-rke2r1-e58e49f33617/bin/:$PATH
[root@pvcecs-master ~]# kubectl get pods
```

=== Incorrect Secret Retrieval Command

.Incorrect Command:
```shell
kubectl -n kubernetes-dashboard get sa/admin-user -o 'jsonpath={.secrets[0].name}'
```

.Correct Command:
```shell
kubectl -n kubernetes-dashboard get secret/admin-user-secret -o 'jsonpath={.metadata.name}'
```

=== Secret Token Retrieval Issue

.Incorrect Command:
```shell
/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n kubernetes-dashboard get secret -o 'go-template={{.data.token | base64decode}}'
```

.Correct Command:
```shell
kubectl get secret -n kubernetes-dashboard admin-user-secret -o 'go-template={{.data.token | base64decode}}'
```

=== Helm Installation Failure

.Error Message:
```
INSTALLATION FAILED: cannot re-use a name that is still in use
```

.Solution:
```shell
kubectl delete ns kubernetes-dashboard
```

=== TLS Certificate Verification Error

.Error Message:
```
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

.Solution:
```shell
[root@pvcecs-master ~]# mkdir -p ~/.kube
[root@pvcecsmaster opt]# cp /etc/rancher/rke2/rke2.yaml ~/.kube/config
```

=== Wildcard DNS Setup Issue

.Error Message:
```
HTTPSConnectionPool(host='console-cdp.apps.cldrsetup.local', port=443): Max retries exceeded with url: /api/v1/environments2/createPrivateEnvironment (Caused by NameResolutionError)
```

.Solution:
Ensure wildcard DNS is set up before proceeding with ECS setup.

=== CoreDNS Configuration Fix

.Edit CoreDNS Configuration:
```shell
k edit cm rke2-coredns-rke2-coredns -n kube-system -o yaml
```

.Update Corefile:
```yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
      errors
      health {
          lameduck 5s
      }
      ready
      kubernetes cluster.local cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      }
      prometheus 0.0.0.0:9153
      forward . 172.16.31.226
      cache 30
      loop
      reload
      loadbalance
    }
```

=== ECS Bootstrap Error

.Error Message:
```
[time="2024-03-19T11:10:29-07:00" level=fatal msg="Failed to reconcile with temporary etcd: bootstrap data already found and encrypted with different token"]
```

.Solution:
Ensure a proper cleanup before reinstalling.

== Conclusion
Following these troubleshooting steps will help resolve common issues encountered while managing ECS clusters in Cloudera CDP Private Cloud Data Services.

