= **CDP Private Cloud (PvC) Installation & Setup on VMware**
:doctype: book
:toc: macro
:toc-title: Table of Contents
:toclevels: 3
:sectnums:
:author: Kuldeep Sahu
:email:
:revnumber: 1.0
:revdate: February 2025
:company: Cloudera Inc.

== **Deployment Guide**

*Published: February 2025*

**In partnership with:**

By: ***Kuldeep Sahu***, *Partner Solutions Engineer*, **Cloudera Inc.**

<<<

== **Audience**

The intended audience for this document includes, but is not limited to, **sales engineers, field consultants, professional services, IT managers, IT engineers, partners, and customers** who are interested in learning about and deploying the **Cloudera Data Platform Private Cloud (CDP Private Cloud) on the VMware Platform** for digital transformation through cloud-native modern data analytics and AI/ML.

== **Purpose of this Document**

This document describes the **architecture, installation, configuration, and validated use cases** for the VMware Platform using **Cloudera Data Platform Private Cloud Base** on VMware servers. A **reference architecture** is provided to configure the Cloudera Data Platform on VMware.

<<<

*<<toc,Back to Table of Contents>>*

